// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/healthcare/AppointmentBooking.tsx": () => import("../components/mockups/healthcare/AppointmentBooking.tsx"),
  "./components/mockups/healthcare/DoctorDashboard.tsx": () => import("../components/mockups/healthcare/DoctorDashboard.tsx"),
  "./components/mockups/healthcare/HealthchatBot.tsx": () => import("../components/mockups/healthcare/HealthchatBot.tsx"),
  "./components/mockups/healthcare/LabAI.tsx": () => import("../components/mockups/healthcare/LabAI.tsx"),
  "./components/mockups/healthcare/LoginPage.tsx": () => import("../components/mockups/healthcare/LoginPage.tsx"),
  "./components/mockups/healthcare/PatientDashboard.tsx": () => import("../components/mockups/healthcare/PatientDashboard.tsx"),
  "./components/mockups/healthcare/SignupPage.tsx": () => import("../components/mockups/healthcare/SignupPage.tsx"),
  "./components/mockups/healthcare/SmartPrescription.tsx": () => import("../components/mockups/healthcare/SmartPrescription.tsx"),
  "./components/mockups/healthcare/SuperAdminDashboard.tsx": () => import("../components/mockups/healthcare/SuperAdminDashboard.tsx")
};
